auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  replication_factor: 1

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

schema_config:
  configs:
    - from: 2020-10-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

# Use memberlist for ring coordination (single-node setup)
memberlist:
  join_members:
    - "127.0.0.1"

# Configure distributor to use memberlist rather than Consul
distributor:
  ring:
    kvstore:
      store: memberlist

# Configure ingester to use memberlist for ring state
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
