global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']  # cAdvisor (Docker metrics)

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # Node Exporter (System metrics)

  - job_name: promtail
    honor_timestamps: true
    static_configs:
      - targets:
          - "intelnuc.local:9080"