global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9109']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8089']

  - job_name: 'traefik'
    static_configs:
      - targets: ['localhost:8082']
    metrics_path: /metrics
